#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")" >/dev/null

npx prettier@2.3.2 -w 'version' 'bench/*.{js,json}' 'bench/*/*.{js,json}' 'gen/*.{ts,json}'

for dir in \
  bench/runners/minify-html \
  bench/runners/minify-html-onepass \
  cli \
  fuzz \
  fuzz/process \
  java \
  nodejs/native \
  python \
  ruby \
  rust/main \
  rust/onepass \
; do
  pushd "$dir" >/dev/null
  cargo fmt
  popd >/dev/null
done

popd >/dev/null
