#!/usr/bin/env node

"use strict";

const { readFileSync, writeFileSync } = require("fs");
const { spawnSync } = require("child_process");

// Use minify-html as source of truth for current version value.
const currentVersion = /^version = "(\d+)\.(\d+)\.(\d+)"\s*$/m
  .exec(readFileSync(`${__dirname}/minify-html/Cargo.toml`, "utf8"))
  .slice(1)
  .map((n) => Number.parseInt(n, 10));

const assertBetween = (n, min, max) => {
  if (n < min || n > max) {
    throw new Error("Invalid argument");
  }
  return n;
};

const newVersion = currentVersion.slice();
let versionPart = assertBetween(
  ["major", "minor", "patch"].indexOf(process.argv[2].toLowerCase()),
  0,
  2
);
newVersion[versionPart++]++;
while (versionPart < 3) {
  newVersion[versionPart++] = 0;
}

console.log(`${currentVersion.join(".")} => ${newVersion.join(".")}`);

const NEW_VERSION = newVersion.join(".");

const cmd = (...cfg) => {
  const command = cfg[0];
  const args = cfg.slice(1);
  const {
    workingDir,
    throwOnBadStatus = true,
    throwOnSignal = true,
    captureStdio = false,
    throwOnStdErr = false,
  } = typeof args[args.length - 1] == "object" ? args.pop() : {};

  const throwErr = (msg) => {
    throw new Error(`${msg}\n  ${command} ${args.join(" ")}`);
  };

  const { status, signal, error, stdout, stderr } = spawnSync(
    command,
    args.map(String),
    {
      cwd: workingDir,
      stdio: [
        "ignore",
        captureStdio ? "pipe" : "inherit",
        captureStdio || throwOnStdErr ? "pipe" : "inherit",
      ],
      encoding: "utf8",
    }
  );
  if (error) {
    throwErr(error.message);
  }
  if (throwOnSignal && signal) {
    throwErr(`Command exited with signal ${signal}`);
  }
  if (throwOnBadStatus && status !== 0) {
    throwErr(`Command exited with status ${status}`);
  }
  if (throwOnStdErr && stderr) {
    throwErr(`stderr: ${stderr}`);
  }
  return { status, signal, stdout, stderr };
};

const replaceInFile = (path, pattern, replacement) =>
  writeFileSync(
    path,
    readFileSync(`${__dirname}/${path}`, "utf8").replace(pattern, replacement)
  );

if (
  cmd("git", "status", "--porcelain", {
    throwOnStderr: true,
    captureStdio: true,
  }).stdout
) {
  throw new Error("Working directory not clean");
}
cmd("git", "pull");
cmd("cargo", "test");

replaceInFile("CHANGELOG.md", /^## Pending$/m, `## ${NEW_VERSION}`);

for (const f of [
  "minhtml/Cargo.toml",
  "minify-html-java/Cargo.toml",
  "minify-html-nodejs/Cargo.toml",
  "minify-html-onepass-python/Cargo.toml",
  "minify-html-onepass/Cargo.toml",
  "minify-html-python/Cargo.toml",
  "minify-html-ruby/ext/minify_html/Cargo.toml",
  "minify-html-wasm/Cargo.toml",
  "minify-html/Cargo.toml",
]) {
  replaceInFile(
    f,
    /^version = "\d+\.\d+\.\d+"\s*$/m,
    `version = "${NEW_VERSION}"`
  );
}

for (const f of ["minhtml/Cargo.toml"]) {
  replaceInFile(
    f,
    /^minify-html = \{ version = "\d+\.\d+\.\d+"/m,
    `minify-html = { version = "${NEW_VERSION}"`
  );
}

for (const f of ["README.md", "minify-html-ruby/ext/minify_html/Cargo.toml"]) {
  replaceInFile(f, /^(minify-html = )"\d+\.\d+\.\d+"/m, `$1"${NEW_VERSION}"`);
}

for (const f of ["README.md"]) {
  replaceInFile(
    f,
    /(wilsonl\.in\/minify-html\/(?:bin|deno)\/)\d+\.\d+\.\d+/g,
    `$1${NEW_VERSION}`
  );
}

for (const f of ["minify-html-java/pom.xml", "README.md"]) {
  replaceInFile(
    f,
    /(<artifactId>minify-html<\/artifactId>\s*<version>)\d+\.\d+\.\d+(<\/version>)/,
    `$1${NEW_VERSION}$2`
  );
}

for (const f of ["minify-html-nodejs/package.json"]) {
  replaceInFile(
    f,
    /(\s*"(?:version|@minify-html\/node-.*?)": )"\d+\.\d+\.\d+"(,?\s*)$/gm,
    `$1"${NEW_VERSION}"$2`
  );
}

for (const f of ["minify-html-wasm/deno.json"]) {
  replaceInFile(
    f,
    /(\s*"version": )"\d+\.\d+\.\d+"(,?\s*)$/gm,
    `$1"${NEW_VERSION}"$2`
  );
}

for (const f of ["minify-html-ruby/minify_html.gemspec"]) {
  replaceInFile(
    f,
    /^(\s*spec\.version\s*=\s*)"\d+\.\d+\.\d+"\s*$/m,
    `$1"${NEW_VERSION}"`
  );
}

cmd("git", "add", "-A");
cmd("git", "commit", "-m", NEW_VERSION);
cmd("git", "tag", "-a", `v${NEW_VERSION}`, "-m", "");
cmd("cargo", "publish", { workingDir: `${__dirname}/minify-html` });
cmd("cargo", "publish", { workingDir: `${__dirname}/minify-html-onepass` });
cmd("cargo", "publish", { workingDir: `${__dirname}/minhtml` }); // This must come after the above as it depends on the just-published version of those.
cmd("git", "push", "--follow-tags");
