#ifndef _HDR_HYPERBUILD_STREAM_HELPER_ATTRVAL
#define _HDR_HYPERBUILD_STREAM_HELPER_ATTRVAL

#define HBSH_ATTR_QUOTED 1
#define HBSH_ATTR_UNQUOTED 2
#define HBSH_ATTR_NOVAL 3

#endif // _HDR_HYPERBUILD_STREAM_HELPER_ATTRVAL
