[package]
publish = false
name = "minify-html-java"
version = "0.16.4"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2024"

[dependencies]
minify-html = { path = "../minify-html" }
jni = "0.14.0"

[lib]
crate-type = ["cdylib"]
path = "src/main/rust/lib.rs"
