#pragma once

typedef enum {
	HBE_NO_ERROR = 0,

	HBE_INTERR_UNKNOWN_ENTITY_TYPE = 2,
	HBE_INTERR_UNKNOWN_CONTENT_NEXT_STATE,

	HBE_CLI_TOO_MANY_OPTIONS = 17,
	HBE_CLI_INVALID_TAG_SET,
	HBE_CLI_INVALID_TAG,
	HBE_CLI_INVALID_SUPPRESSABLE_ERROR,

	HBE_IO_FOPEN_FAIL = 33,
	HBE_IO_FCLOSE_FAIL,
	HBE_IO_FREAD_FAIL,
	HBE_IO_FWRITE_FAIL,

	HBE_PARSE_MALFORMED_ENTITY = 65,
	HBE_PARSE_BARE_AMPERSAND,
	HBE_PARSE_INVALID_ENTITY,
	HBE_PARSE_NONSTANDARD_TAG,
	HBE_PARSE_UCASE_TAG,
	HBE_PARSE_UCASE_ATTR,
	HBE_PARSE_UNQUOTED_ATTR,
	HBE_PARSE_ILLEGAL_CHILD,
	HBE_PARSE_UNCLOSED_TAG,
	HBE_PARSE_SELF_CLOSING_TAG,
	HBE_PARSE_NO_SPACE_BEFORE_ATTR,

	HBE_PARSE_UNEXPECTED_END,
	HBE_PARSE_EXPECTED_NOT_FOUND,
} hb_error_t;
