#ifndef _HDR_HYPERBUILD_DATASTRUCTURE_MAP_STR_INT32
#define _HDR_HYPERBUILD_DATASTRUCTURE_MAP_STR_INT32

#include "../../ext/nicehash/map/str.h"

NICEHASH_MAP_STR(int32, int32_t)

#endif // _HDR_HYPERBUILD_DATASTRUCTURE_MAP_STR_INT32
